version: '3.8'
services:
  skorm-bot:
    build: .
    container_name: skorm-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - lavalink

  lavalink:
    build:
      context: ./lavalink
      dockerfile: Dockerfile
    container_name: skorm-lavalink
    restart: unless-stopped
    ports:
      - "2333:2333"
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro

volumes:
  lavalink: