server:
  port: 2333
  ssl:
    enabled: false

lavalink:
  server:
    password: skorm
    sources:
      - youtube
      - soundcloud
      - bandcamp
      - twitch
      - vimeo
      - http
      - local
    bufferDuration: -1
    frameBufferDuration: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThreshold: 10000
    useSeekGetters: true
    youtubePlaylistLoadLimit: 10
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

  plugins:
    - |
      me.kami.lavalink.spotify.SpotifyPluginConfig {
        clientId = "8135bad63143448190f458e0587ba33f"
        clientSecret = "76e07ab4ac2d4e13a37ff561d9d5febd"
      }
