server:
  port: 2333
  ssl:
    enabled: false

lavalink:
  server:
    password: skorm
    sources:
      - soundcloud
      - bandcamp
      - twitch
      - vimeo
      - http
      - local
    bufferDuration: -1
    frameBufferDuration: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThreshold: 10000
    useSeekGetters: true
    youtubePlaylistLoadLimit: 10
    playerUpdateInterval: 5
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: true
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      repository: "https://maven.lavalink.dev/releases"

plugins:
  lavasrc:
    providers:
      - "spsearch:%ISRC%"
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
    spotify:
      clientId: "8135bad63143448190f458e0587ba33f"
      clientSecret: "76e07ab4ac2d4e13a37ff561d9d5febd"
      preferPartnerApi: false
