server:
  port: 2333
  ssl:
    enabled: false

lavalink:
  server:
    password: skorm
    sources:
      - soundcloud
      - bandcamp
      - twitch
      - vimeo
      - http
      - local
    bufferDuration: -1
    frameBufferDuration: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThreshold: 10000
    useSeekGetters: true
    youtubePlaylistLoadLimit: 10
    playerUpdateInterval: 5
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: true
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      repository: "https://maven.lavalink.dev/releases"

plugins:
  lavasrc:
    providers:
      - "spsearch:%ISRC%"
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET}"
      preferPartnerApi: false
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    allowPlaylist: true
    clientStyle: "IOS"
    loopingDecipher: true
    retryCount: 10
